steps:
  - label: "Run tests"
    command: |
      (cd .buildkite/image && \
        docker build \
          --build-arg UID=$(id -u $USER) \
          --build-arg USER=$USER \
          -t tweag/rules_sh:latest \
          .)
      docker run -it \
        --network host \
        -v $(pwd):/home/$USER/rules_sh:rw \
        --workdir /home/$USER/rules_sh \
        tweag/rules_sh:latest \
        .buildkite/run-pipeline
    timeout: 30
