name: Continuous integration
on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '1 11 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build-and-test:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]
        bazel_mode: [workspace, module]
        version: ["5.3.0", "6.0.0", "7.0.0"]
        exclude:
          - version: 5.3.0
            bazel_mode: module
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v2
      - uses: tweag/configure-bazel-remote-cache-auth@v0
        with:
          buildbuddy_api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
          bazelrc_path: .bazelrc.auth
      - uses: extractions/netrc@v1
        with:
          machine: api.github.com
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure
        run: |
          cat >>.bazelrc.local <<-EOF
          build --config=ci
          EOF
          cat >~/.netrc <<-EOF
          machine api.github.com
                  password ${{ secrets.GITHUB_TOKEN }}
          EOF
          if [[ ${{ runner.os }} == Windows ]]; then
            # Stardoc complains about docstring quote indentation on Windows.
            cat >>.bazelrc.local <<-EOF
          build --config=no-stardoc
          EOF
          fi
          if [[ ${{ matrix.bazel_mode }} == module ]]; then
            # Stardoc does not work with bzlmod.
            cat >>.bazelrc.local <<-EOF
          build --config=no-stardoc
          EOF
            # Test with bzlmod enabled.
            cat >>.bazelrc.local <<-EOF
          build --experimental_enable_bzlmod
          EOF
          fi

      # TODO: REMOVE ME!
      - name: DEBUG
        shell: bash
        run: |
          cat >&2 .bazelrc.local

      - name: Run tests (bzlmod)
        if: matrix.bazel_mode == 'module'
        working-directory: ./tests
        run: |
          echo "USE_BAZEL_VERSION=${{ matrix.version }}" > .bazeliskrc

          if [[ ${{ runner.os }} == Windows ]]; then
            # On Windows `//...` expands to `/...`.
            BAZEL_SH='C:\msys64\usr\bin\bash.exe' bazel test  ///...
          else
            bazel test  //...
          fi

      - name: Run tests (workspace)
        if: matrix.bazel_mode == 'workspace'
        run: |
          echo "USE_BAZEL_VERSION=${{ matrix.version }}" > .bazeliskrc
          echo "USE_BAZEL_VERSION=${{ matrix.version }}" > tests/.bazeliskrc

          if [[ ${{ runner.os }} == Windows ]]; then
            # Because of the docstring quote issue on Windows we skip the stardoc test on the main workspace.
            # On Windows `//...` expands to `/...`.
            cd tests && BAZEL_SH='C:\msys64\usr\bin\bash.exe' bazel test ///...
          else
            bazel test //...

            cd tests && bazel test //...
          fi

  all_ci_tests:
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    if: ${{ always() }}
    steps:
      - uses: cgrindel/gha_join_jobs@794a2d117251f22607f1aab937d3fd3eaaf9a2f5 # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
